### ISSUE TITLE
Settings not persistent across sessions?

### ISSUE THREAD

**Issue by DrGomek** [kjarmicki/attributes-replacer#1]
I am able to set up a robust replace of attributes to my liking, and it works perfectly.

However, it seems that the settings are not persistent and I'm constantly having to re-enter them.

**Comment by kjarmicki** [comment]
Hi, thanks for the report :)

I've spotted a bug that might have caused the behavior you're describing. Please update to version 1.1.1 (should be in Chrome Webstore now) across all the devices you're using.

**Comment by DrGomek** [comment]
Yes, 1.1.1 fixes my problem.  Thank you!

**Comment by kjarmicki** [comment]
:+1:

**Comment by mmortal03** [comment]
Could be a new issue, but I noticed that while the Replacing option is staying on, it's not applying to pages until I turn it off and back on.

**Comment by kjarmicki** [comment]
@mmortal03 you mean you're on one page, replacing is on, you switch to another tab and expect attributes on that page to be changed as well?

**Comment by mmortal03** [comment]
Yeah, I mean, I could see a potential for excessive resource usage with applying it to *every* page, but, for example, with that CNN caption issue that I'm still experiencing, I don't want to have to go and turn attributes-replacer off and on, or on and off, for every CNN video URL (because, at that point, I might as well just click to turn off the captions on the video itself). 

I guess having some way to have it automatically apply for specific URLs could work (something like www.cnn.com/videos/*) -- you get the idea. I recall using Proxomitron back in the day; maybe I should break that back out, even though it's 13 years old! :) Greasemonkey might also work. Both of those options seem overkill for this purpose, though.

**Comment by kjarmicki** [comment]
@mmortal03 that's true and it's a reasonable feature request. The reason I've asked is I didn't anticipated such use case before, but now that you've mentioned it, it seems really obvious.
I don't think it'd consume much resources as it'd be done lazily (per tab change). Also, I don't want to introduce special syntax for it on a rule level, I've already received complaints that it's too complicated ;) I'll assume that `on` means `on for all tabs`, because it looks that way in the UI too, as you've pointed out.

Let's keep this issue closed and continue discussion here: #3
